# Generated by Django 2.2.3 on 2019-07-12 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EProd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('qty', models.IntegerField()),
                ('price', models.FloatField()),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'eprod_info',
            },
        ),
        migrations.CreateModel(
            name='EVend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('code', models.IntegerField()),
            ],
            options={
                'db_table': 'evend_info',
            },
        ),
    ]
